# Site settings é…ç½®ç«™ç‚¹
title: 'å¥”è·‘çš„å°çŒªğŸ·'
description: 'ä¸€ä¸ªä¼šåšé¥­çš„åç«¯ã€‚'
keyword: 'Javaï¼ŒLOL'
url: 'https://gaoshuai991.github.io' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# åœ¨æœåŠ¡å™¨ä¸Šå»ºç«™æ—¶ï¼Œå¦‚æœä½ ä¸éœ€è¦å­åŸŸåï¼Œè¯·å°†è¿™ä¸€æ ¼ç•™ç©º
# if you're using GitHub Pages, set baseurl to your blog's .
# å¦‚æœä½ åœ¨ä½¿ç”¨ GitHub Pages, è¯·å°† baseurl è®¾ç½®ä¸ºä½ çš„ç½‘å€çš„å­åŸŸå
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# ä¾‹å¦‚ï¼Œå½“ä½ çš„åŸŸåæ˜¯ "kaeyleo.github.io"  æ—¶ï¼Œè¿™ä¸ª url éœ€è¦ç•™ç©º
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# ä½†æ˜¯ï¼Œå¦‚æœä½ åˆ›å»ºäº†ä¸€ä¸ªå« "myblog" çš„ç½‘ç«™ï¼Œæ­¤æ—¶ç½‘å€ä¼šå˜æˆ "kaeyleo.github.io/myblog" ï¼Œè¿™æ—¶å†å°† baseurl è®¾ç½®ä¸º '/myblog'
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2019

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'å¥”è·‘çš„å°çŒª'
nickname: 'ğŸ·'
bio: 'ä¸€ä¸ªä¼šåšé¥­çš„åç«¯'
avatar: '/assets/img/xiaozhu.jpg'

# Search
search: true

# Night mode
nightMode: false

# Comments è¯„è®ºåŠŸèƒ½
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax å…¬å¼æ”¯æŒ by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['weibo']

# theme color ä¸»é¢˜çš®è‚¤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/gaoshuai991'

# Tags è®¾ç½®æ ‡ç­¾
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
